### ISSUE TITLE
cartopy dependency is too restrictive

### ISSUE THREAD

**Issue by aidanheerdegen** [nicrie/xmca#29]
The [very restrictive cartopy dependency](https://github.com/coecms/xmca/blob/main/requirements.txt#L5) makes it tricky to install into an existing `conda` environment
```python
cartopy==0.18.0
```
I can see it was changed at https://github.com/coecms/xmca/commit/896e0b5977c4f4a36ed01363141f3ab7dd24c6d5

When I changed it back to `>=18.0` it installed fine using `pip install --user` and imported fine with `cartopy-0.19.0.post1`.

I ran the tests like so
```bash
python -m unittest discover -v -s tests/
```
but three of the tests didn't pass
```
test_save_load_cplx (integration.test_integration_xarray.TestIntegration) ... ERROR    
test_save_load_rot (integration.test_integration_xarray.TestIntegration) ... ERROR                                       
test_save_load_std (integration.test_integration_xarray.TestIntegration) ... ERROR    
```
Some other error messages:
```
Error: Rotation process did not converge!

======================================================================                                                   
ERROR: test_save_load_cplx (integration.test_integration_xarray.TestIntegration)                                         
----------------------------------------------------------------------                                                   
Traceback (most recent call last):
  File "/home/502/aph502/.local/lib/python3.9/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/502/aph502/code/python/xmca/tests/integration/test_integration_xarray.py", line 148, in test_save_load     
    rmtree(join(getcwd(), 'tests/integration/temp/'))
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/shutil.py", line 731, in rmtree           
    onerror(os.rmdir, path, sys.exc_info())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/shutil.py", line 729, in rmtree           
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/502/aph502/code/python/xmca/tests/integration/temp/'                     

======================================================================                                                   
ERROR: test_save_load_rot (integration.test_integration_xarray.TestIntegration)                                          
----------------------------------------------------------------------                                                   
Traceback (most recent call last):
  File "/home/502/aph502/.local/lib/python3.9/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/502/aph502/code/python/xmca/tests/integration/test_integration_xarray.py", line 148, in test_save_load     
    rmtree(join(getcwd(), 'tests/integration/temp/'))
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/shutil.py", line 731, in rmtree           
    onerror(os.rmdir, path, sys.exc_info())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/shutil.py", line 729, in rmtree           
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/502/aph502/code/python/xmca/tests/integration/temp/'                     

======================================================================                                                   
ERROR: test_save_load_std (integration.test_integration_xarray.TestIntegration)                                          
----------------------------------------------------------------------                                                   
Traceback (most recent call last):
  File "/home/502/aph502/.local/lib/python3.9/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/502/aph502/code/python/xmca/tests/integration/test_integration_xarray.py", line 148, in test_save_load     
    rmtree(join(getcwd(), 'tests/integration/temp/'))
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/shutil.py", line 731, in rmtree           
    onerror(os.rmdir, path, sys.exc_info())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/shutil.py", line 729, in rmtree           
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/502/aph502/code/python/xmca/tests/integration/temp/'                     

---------------------------------------------------------------------- 
```
but it wasn't obvious that this was an issue with the version of ``cartopy``.

**Comment by nicrie** [comment]
Thank you @aidanheerdegen for pointing this out!  

### In short
I have uploaded version `1.4.2`  (#30 ) with some changes that address your points.

### A little more background

I don`t remember the exact `cartopy` version, but at the time of testing the last `cartopy` version (I think it was `0.19.z`) broke the installation. I couldn`t figure out how to avoid this, so I decided to use the (admittedly) too restrictive version constraint. Now that there are newer versions that work, you are probably right to remove that restriction. 

As for the error messages in the test suite, two things seem to happen: 

1) The test suite runs a series of tests to check that an analysis it has run is saved/loaded correctly. The analyses are stored in a temporary folder `xmca/tests/integration/temp/` which is automatically deleted after each test with `shutil.rmtree`. It seems that deleting this folder fails. I cannot reproduce this problem, on my Linux system everything runs fine. But if you use Windows in combination with Python 3.9, a similar problem has been reported [here](https://bugs.python.org/issue40143). Unfortunately, I couldn't find a quick solution for this problem, as I don't have a Windows machine at hand for testing. However, since the error is only caused by an incorrectly deleted "temp" folder, I think it can be safely ignored.
2) `Error: Rotation process did not converge!` is output when the rotation fails, but should actually trigger an error. For random datasets created with bootstrapping methods, rotation can sometimes fail. I have changed this in version `1.4.2` which will throw an error if rotation fails. At the same time, the bootstrapping method will catch this error and simply continue with the next iteration, which should make the printed error message disappear.

____________________
*Note:* `xmca` was my first project, and although all the methods should work correctly, the overall structure of the package is not very clean from a coding point of view, making further development difficult.

Recently I have released [`xeofs`](https://github.com/nicrie/xeofs), the aim of which is to bring together all the EOF analysis techniques (including all the current functionality of `xmca`), but based on a more solid coding framework. So I hope that `xmca` as a package will eventually become obsolete. If you are interested, just watch the relevant repository.

**Comment by aidanheerdegen** [comment]
Awesome. For a first package that is an impressive amount of testing.

I was trying to install this for someone else in a shared `conda` environment we use at our HPC centre. In the end it was necessary for them to `pip install` with `--user`, but it would be great to have `xeofs` in something like `conda-forge` to make it more widely available.

**Comment by nicrie** [comment]
Thanks for the suggestion - I'd really like to put it on `conda-forge` but don't know when I'll have the time to do so. 
I guess for the moment this issue here is fixed, just let me know if you encounter other problems.
