### ISSUE TITLE
May cause errors after using mca. normalize()

### ISSUE THREAD

**Issue by L1angY** [nicrie/xmca#33]
Hello, first of all, thank you for your contribution. However, I found a bug that may cause SVD to fail to calculate (due to the existence of NaN value). The details are as follows: 

when MCA class is initialized, it will be called **get_nan_cols** and **remove_ nan_ cols** to remove the NaN value, but if you call **mca.normalize()** at this time. New NaN values can appear and be brought into SVD calculation. This is because if the value of each time step of a grid point in the input array is the same (For example, it never rains in a place), the value obtained after standardization is NaN, which causes SVD unable to solve problem.

**Comment by nicrie** [comment]
Yes that's indeed true - thanks for catching this and raising the issue! :)
Currently, I am migrating xmca to the newer [xeofs](https.//github.com/nicrie/xeofs) package. This issue is solved there and should not make problems. Most of the functionalities (except complex PCA/MCA) are also available in xeofs. So perhaps you want to give it a try. Currently I am not planning to keep updating xmca.

**Comment by L1angY** [comment]
> Yes that's indeed true - thanks for catching this and raising the issue! :) Currently, I am migrating xmca to the newer [xeofs](https.//github.com/nicrie/xeofs) package. This issue is solved there and should not make problems. Most of the functionalities (except complex PCA/MCA) are also available in xeofs. So perhaps you want to give it a try. Currently I am not planning to keep updating xmca.

This is great. Thank you for your selfless contribution. If I have a new paper to publish, I will quote it!
